### ISSUE TITLE
[BUG REPORT] The app crashes when I try to open it.

### ISSUE THREAD

**Issue by ahmednasser293** [Akylas/OSS-DocumentScanner#265]
### Version

1.10.0.88

### What platform are you using?

Android

### OS Version

Android 14, Xiaomi HyperOS

### What happened?

When I try to open the app on my Xiaomi phone, it crashs immediately.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DebarghayaMitra** [comment]
Also had same issue in POCO F6
Xiaomi HyperOS version 1.0.3.0.UNPINXM
Android version 14

The crash mainly occurs when biometric lock is turned on and when files are selected from file manager instead of capturing directly in both Card and Docs app.

Cards app diagnostics report ⬇️

![Screenshot_2024-07-20-14-01-55-982_com.miui.bugreport.jpg](https://github.com/user-attachments/assets/6a3f4549-bd01-44b8-9dee-46d0cd539a98)

Docs app diagnostic report ⬇️

![Screenshot_2024-07-20-14-02-31-585_com.miui.bugreport.jpg](https://github.com/user-attachments/assets/4b95e5ae-dbda-4d84-9047-f0a9ecdc0c38)

**Comment by farfromrefug** [comment]
@DebarghayaMitra @ahmednasser293 I just released a new build which hopefully fixed it.
I am really sorry about this!
Let me know if it works

**Comment by FurhadTheNerd** [comment]
I'm having the same problem, i have a pixel 6 running android 14 (AP2A.240705.004) rooted with magisk, i have biometric on and lots of vert important documents, here's the crash log

FATAL EXCEPTION: main
Process: com.akylas.documentscanner, PID: 15308
com.tns.NativeScriptException: Calling js method onStart failed
Error: java.lang.Exception: Failed resolving constructor for class 'com.airbnb.lottie.SimpleColorFilter' with 1 parameters. Check the number and type of arguments.
Primitive types need to be manually wrapped in their respective Object wrappers.
If you are creating an instance of an inner class, make sure to always provide reference to the outer `this` as the first argument.
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:1)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:100)
	at com.tns.Runtime.callJSMethod(SourceFile:1)
	at com.tns.Runtime.callJSMethod(SourceFile:2)
	at com.tns.Runtime.callJSMethod(SourceFile:3)
	at com.tns.gen.androidx.fragment.app.DialogFragment_vendor_37_213318_i.onStart(Unknown Source:7)
	at androidx.fragment.app.Fragment.performStart(SourceFile:18)
	at androidx.fragment.app.h0.k(SourceFile:97)
	at androidx.fragment.app.FragmentManager.L(SourceFile:58)
	at androidx.fragment.app.FragmentManager.u(SourceFile:34)
	at androidx.fragment.app.FragmentController.dispatchStart(SourceFile:15)
	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:37)
	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:1)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:100)
	at com.tns.Runtime.callJSMethod(SourceFile:1)
	at com.tns.Runtime.callJSMethod(SourceFile:2)
	at com.tns.Runtime.callJSMethod(SourceFile:3)
	at com.akylas.documentscanner.MainActivity.onStart(Unknown Source:7)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1701)
	at android.app.Activity.performStart(Activity.java:9003)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4018)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.Exception: Failed resolving constructor for class 'com.airbnb.lottie.SimpleColorFilter' with 1 parameters. Check the number and type of arguments.
Primitive types need to be manually wrapped in their respective Object wrappers.
If you are creating an instance of an inner class, make sure to always provide reference to the outer `this` as the first argument.
	at com.tns.Runtime.resolveConstructorSignature(SourceFile:62)
	... 37 more

**Comment by DebarghayaMitra** [comment]
@farfromrefug it seems to be working

**Comment by ahmednasser293** [comment]
> @DebarghayaMitra @ahmednasser293 I just released a new build which hopefully fixed it.
> I am really sorry about this!
> Let me know if it works

Thanks it works perfectly now ❤️
