### ISSUE TITLE
App Crashes when Biometrics are turned on or images are selected from gallery

### ISSUE THREAD

**Issue by DebarghayaMitra** [Akylas/OSS-DocumentScanner#266]
### Version

Doc Scanner Version 1.10.0 build 88
Card Scanner Version 1.1.0 build 9

### What platform are you using?

Android

### OS Version

Xiaomi HyperOS version 1.0.3.0.UNPINXM
Android Version 14

### What happened?

A bug happened! Both apps Crashes when Biometrics are turned on or images are selected from gallery

logs for cards app

![Screenshot_2024-07-20-14-01-55-982_com miui bugreport](https://github.com/user-attachments/assets/e048374e-e067-4ddc-94e2-3a14a7fd46cf)

logs for docs app

![Screenshot_2024-07-20-14-02-31-585_com miui bugreport](https://github.com/user-attachments/assets/f4255d3c-6172-4b99-ab37-50651cc1dc63)

### Relevant log output

```shell
logs for cards app

com.tns.NativeScriptException: Calling js method onStart failed

Error: java.lang.Exception: Failed resolving constructor for

class 'com.airbnb.lottie.SimpleColorFilter' with 1 parameters.

Check the number and type of arguments.

Primitive types need to be manually wrapped in their respective Object wrappers.

If you are creating an instance of an inner class, make sure to always provide reference to the outer 'this' as the first

argument. at com.tns.Runtime.callJSMethodNative(Native Method)

at

com.tns.Runtime.dispatchCallJSMethodNative (SourceFile:17 )

at com.tns.Runtime.callJSMethodImpl(SourceFile:101)

at com.tns.Runtime.callJSMethod(SourceFile:7) at com.tns.Runtime.callJSMethod (SourceFile:2)

at com.tns.Runtime.callJSMethod(SourceFile:1)

at

com.tns.gen.androidx.fragment.app.DialogFragment_vendo

r_3463_22_n.onStart(SourceFile:8)

at 8) androidx.fragment.app.Fragment.performStart(SourceFile:1

at androidx.fragment.app.h0.k(SourceFile:97)

androidx.fragment.app.FragmentManager.u(SourceFile:34)

at androidx.fragment.app.FragmentManager.L(SourceFile:58)

at

at

urceFile:15) androidx.fragment.app.FragmentController.dispatchStart(So

at

38) androidx.fragment.app.FragmentActivity.onStart(SourceFile:

at

androidx.appcompat.app.AppCompatActivity.onStart(Sourc eFile:1)

at com.tns.Runtime.callJSMethodNative(Native Method)

at

com.tns.Runtime.dispatchCallJSMethodNative (SourceFile:17 ) at com.tns.Runtime.callJSMethodImpl(SourceFile:101) at com.tns.Runtime.callJSMethod (SourceFile:7)

at com.tns.Runtime.call.JSMethod (SourceFile:2)

at com.tns.Runtime.callJSMethod(SourceFile:1) at com.akylas.cardwallet.MainActivity.onStart(SourceFile:8)

at

android.app.Instrumentation.callActivityOnStart(Instrument ation.java:1597 )

at android.app.Activity.performStart(Activity.java:8931) at

android.app.ActivityThread.handleStartActivity(ActivityThrea d.java:4016)

at

android.app.servertransaction.Transaction Executor.perform

LifecycleSequence (Transaction Executor.java:235) at

android.app.servertransaction.Transaction Executor.cycleToP

ath(TransactionExecutor.java:215)

at android.app.servertransaction.TransactionExecutor.executeL

ifecycleState(TransactionExecutor.java:187) at

android.app.servertransaction.TransactionExecutor.execute( Transaction Executor.java:101)

at

android.app.ActivityThread$H.handleMessage(ActivityThrea d.java:2589)

at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop Once(Looper.java:224)

at

android.os.Looper.loop (Looper.java:318)

at android.app.ActivityThread.main(ActivityThread.java:8790)

at java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.RuntimeInit$MethodAndArgsCaller. run(RuntimeInit.java:561)

at

at

) com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013

Caused by: java.lang.Exception: Failed resolving constructor for class 'com.airbnb.lottie.SimpleColorFilter' with 1

parameters. Check the number and type of arguments. Primitive types need to be manually wrapped in their

respective Object wrappers.

If you are creating an instance of an inner class, make sure to always provide reference to the outer 'this' as the first

argument.

at

com.tns.Runtime.resolveConstructor Signature (SourceFile:6 2)

36 more



logs for docs app

com.tns.NativeScriptException: Calling js method onStart failed

Error: java.lang.Exception: Failed resolving constructor for

class 'com.airbnb.lottie.SimpleColorFilter' with 1 parameters.

Check the number and type of arguments.

Primitive types need to be manually wrapped in their respective Object wrappers.

If you are creating an instance of an inner class, make sure to always provide reference to the outer 'this as the first

argument.

at com.tns.Runtime.callJSMethodNative(Native Method) at

com.tns.Runtime.dispatchCallJSMethodNative (SourceFile:17 )

at com.tns.Runtime.call.JSMethodImpl(SourceFile:101)

at com.tns.Runtime.call.JSMethod(SourceFile:7) at com.tns.Runtime.callJSMethod(SourceFile:2)

at com.tns.Runtime.callJSMethod(SourceFile:1)

at

com.tns.gen.androidx.fragment.app.DialogFragment_vendo r_3463_22_n.onStart(SourceFile:8)

at 8) androidx.fragment.app.Fragment.performStart(SourceFile:1

at androidx.fragment.app.h0.k(SourceFile:97)

androidx.fragment.app.FragmentManager.u(SourceFile:34) at

at androidx.fragment.app.FragmentManager.L(SourceFile:58)

at urceFile:15) androidx.fragment.app.FragmentController.dispatchStart(So

at 38) androidx.fragment.app.FragmentActivity.onStart(SourceFile:

at

androidx.appcompat.app.AppCompatActivity.onStart(Sourc eFile:1) at com.tns.Runtime.callJSMethodNative(Native Method)

at com.tns.Runtime.dispatchCallJSMethodNative (SourceFile:17

at com.tos.Runtime.calJSMethodImpl(SourceFile:101)

at com.tns.Runtime.callJSMethod (SourceFile:7) at com.tns.Runtime.callJSMethod(SourceFile:2) at com.tns.Runtime.callJSMethod(SourceFile:1)

at com.akylas.documentscanner.MainActivity.onStart(SourceFil e:8)

at

android.app.Instrumentation.callActivityOnStart(Instrument

ation.java:1597) at android.app.Activity.performStart(Activity.java:8931)

at android.app.ActivityThread.handleStartActivity(ActivityThrea

d.java:4016)

at

android.app.servertransaction.TransactionExecutor.perform LifecycleSequence (Transaction Executor.java:235)

at

android.app.servertransaction.Transaction Executor.cycleToP ath(TransactionExecutor.java:215)

at

android.app.servertransaction.Transaction Executor.executel ifecycleState(TransactionExecutor.java:187)

at android.app.servertransaction.TransactionExecutor.execute(

TransactionExecutor.java:101) at

android.app.ActivityThread$H.handleMessage (ActivityThrea d.java:2589)

at android.os.Handler.dispatchMessage(Handler.java:106)

at android.os.Looper.loop Once(Looper.java:224) at android.os.Looper.loop(Looper.java:318)

at

android.app.ActivityThread.main(ActivityThread.java:8790) at java.lang.reflect.Method.invoke(Native Method)

at

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.

run(RuntimeInit.java:561)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013

Caused by: java.lang.Exception: Failed resolving constructor

for class 'com.airbnb.lottie.SimpleColorFilter' with 1

parameters. Check the number and type of arguments. Primitive types need to be manually wrapped in their

respective Object wrappers.

If you are creating an instance of an inner class, make sure to always provide reference to the outer 'this as the first

argument.

at

com.tns.Runtime.resolveConstructor Signature (SourceFile:6

2)

36 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@DebarghayaMitra hopefully it is fixed in just released new verison. Let me know

**Comment by DebarghayaMitra** [comment]
@farfromrefug it seems to be working
thanks for solving it

i appreciate such a speedy recovery
