### ISSUE TITLE
[BUG] OSS Card Wallet v1.4.0 Build 25 Crash On Startup

### ISSUE THREAD

**Issue by Quince-Pie** [Akylas/OSS-DocumentScanner#353]
### Which app is your issue for

OSS Card Wallet

### Version

OSS Card Wallet(android): v1.4.0 Build 25
app-arm64-v8a-release.apk

### What platform are you using?

Android

### OS Version

Android 15 (GrapheneOS 2024112700)

### What happened?

Latest release (from github releases/Obtainium) crash at startup

### Relevant log output

```shell
type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241105.007/2024112700:user/release-keys
flags: dev options enabled
package: com.akylas.cardwallet:25, targetSdk 34
process: com.akylas.cardwallet
processUptime: 356 + 242 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.akylas.cardwallet/com.akylas.cardwallet.MainActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Main entry is missing. App cannot be started. Verify app bootstrap.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4061)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4248)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2645)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Main entry is missing. App cannot be started. Verify app bootstrap.
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:1)
	at com.tns.Runtime.callJSMethodImpl(Unknown Source:100)
	at com.tns.Runtime.callJSMethod(SourceFile:1)
	at com.tns.Runtime.callJSMethod(SourceFile:2)
	at com.tns.Runtime.callJSMethod(SourceFile:3)
	at com.akylas.cardwallet.MainActivity.onCreate(SourceFile:1)
	at android.app.Activity.performCreate(Activity.java:9055)
	at android.app.Activity.performCreate(Activity.java:9033)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1536)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4043)
	... 15 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@Quince-Pie thanks for reporting and really sorry! fix is building right now.
Will be published tomorrow on izzydroid though. Github and playstore coming soon

**Comment by Quince-Pie** [comment]
@farfromrefug Thank you for the quick response, you're amazing. The new GH release fixes the crash for me.
